name: Lint React App

on:
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Adjust the Node.js version as needed

      - name: Install Dependencies
        run: npm install  # Or use yarn if you prefer

      - name: Run Linting
        run: npm run lint  # Adjust the command based on your project setup
